reformat nicely, add "unless" for idempotency
remove finaly ',' so this will work on ruby 1.8.7
and reformat it nicely. unfortunately, it doesn't work yet...

    igalic@levix ~ % puppet apply --trace -e " git_config { 'alias.switch=checkout': } "
    Notice: Compiled catalog for levix.box in environment production in 0.03 seconds
    Error: Got nil value for name
    /home/igalic/.gem/ruby/2.1.2/gems/puppet-3.6.2/lib/puppet/type.rb:646:in `[]='
    /home/igalic/.gem/ruby/2.1.2/gems/puppet-3.6.2/lib/puppet/type.rb:2224:in `set_name'
    /home/igalic/.gem/ruby/2.1.2/gems/puppet-3.6.2/lib/puppet/type.rb:2196:in `initialize'
    /home/igalic/.gem/ruby/2.1.2/gems/puppet-3.6.2/lib/puppet/resource.rb:314:in `new'
    ...